### ISSUE TITLE
Review of model plugin tutorial

### ISSUE THREAD

**Issue by butlerpd** [SasView/tutorials#4]
Since there is no pull request to use to comment with I thought I'd just start an issue with my comments:

Overall I like it!! It is, as always, very nicely done and should help a lot.  I was worried about bundling every layer into one big tutorial but maybe that is OK now that I've gone through it? Given that it is however a bit long I do have a number of comments which are listed based on the page it appears:

* Page 5 - Checking “overwrite” if the model is a built-in model could be a disaster, however it seems to just fail without announcing (i.e. fails but doesn’t pop up a box and exists the editor). I don’t know what happens if you do this with the simple model editor however.
* Page 6 - Actually @ should normally be used for all P*S unless you
  a) want only constrained radius and no beta approximation option and
  b) want to simplify the model interface.  Using @ does NOT leave radius unconstrained but offers all the usual options (unconstrained, constraint 1, 2, etc) and also offers an option to either use the beta approximation, if available, or not.  To be honest, I think * is just there for completeness and historical reasons.
* Page 11 and 12 - Actually you do **not** need to assign Intensity to y since you explicitly return y. So I frequently do:
```python
Intensity = A * sin(x)
Return intensity
```
Which works just fine.
* Page 14 - Should mention what unit tests are for (not just say it is bad form to ignore). But it is described in section 6 along with appropriate references so here just a sentence about it followed by “see discussion in section 6" would be appropriate I think.
* Page 16 - Actually I don’t think you ever need to import math. That is done automatically somewhere in sasmodels I think?  Certainly you just need to use `cos(x)` or `sin(x)` etc without importing anything.
For the “easy editor” specifically (Because it is meant to be “easy” 🙂 as long as you type `np.array` for example the editor will automatically add the `import numpy as np` statement for you. (note that the file created by the editor automatically adds a `from numpy imp inf`). Finally writing something like `scipy.special.gamma(3)` will get the editor to automatically add an `import scipy` statement.”  This will not be the case of course when creating models from scratch (a different editor) 
  * WARNING HERE. You don’t add polydispersity in the example, but do mention it. It is probably worth noting that IF you declare something polydisperse (type volume) you need to provide a form_volume function later by going to the full model editor **AND** you need to write the function **WITHOUT** normalizing by volume which must get done by SasView to return the number average like all other models. If you do not, the returned value is the z average – this can be discussed in detail here or in section 6 where it appears again. Eventually I’m hoping we can add a pane that pops up as soon as polydisperse parameters are defined and asks for the code for form_volume. For now it is a bit of a dangerous trap for novice users.
* Page  16 - The sentence motivating example 4 seems off… what does the model marketplace have to do with having something in the base models? I don’t understand what this means so guess nor will a new user? 
* Page 17 - Name attribute. As far as I know it is still the name used internally by SasView so needs to be unique. Best if it matches exactly the .py name I think. that is mentioned much later but probably should be done here too? Particularly since the nature of this tutorial means some people may pick and choose which section is appropriate to them?
* Page 17 (and future like page 22/ Example 5) - SasView provides everything you need!! Why open a text editor or the file explorer etc) when you can just use the model editor and load any .py file in the plugin folder (or elsewhere for that matter using the plugin manager!!!)
  * So for example 4 I would open the Manage Custom Models panel and click add file. From there navigate to the folders exactly as you describe. Pick the model and click on it. The beauty of this tool is that if the model is a python plus c, the manager will copy BOTH files to the plugin folder instantly. Because the model name exists it will automatically rename it to model_user internally, however it does not actually change the name of the file or the model name. I think, however, that this still works? But likely you will want to change the name anyway? Now choosing the model and clicking Edit will bring up the Editor  …. With BOTH the py and c files already loaded if they exist. Of course for example 4 only the python file.  The downside is that we currently do not have a button to rename the file (I don’t think?).  From the Editor which has line numbers you can edit and apply etc.. 
    * We wrote these very useful tools so we should be encouraging people to use them (otherwsie they won’t know they exist). I think I would just add a sentence that states “you are of course welcome to use any editor of your choice if you prefer, but will need to restart SasView …”
* Page 16-17 - It may be a question of too much information at this point, but since model marketplace was mentioned, another place to get the models from is said marketplace? But maybe not.. Maybe TMI? In particular since we should focus on using the model manager which will get the files from the local directory.
* Page 24/25 - NICE showing polydisperse (R) vs not poly (Rg).  What happens if you define Rg as “volume” that could be an interesting pedagogical exercise?
* Page 26 - The “next three definitions are optional” should be folded in with the 2 new ones from “the Model Computation” and put in one place. All control the model computation in some way. Each one could be briefly explained (a single phrase). Also `have _Fq` does **not** mean the model requires F(Q), rather it tells sasmodels that the model **has** an F(Q) function defined which sasmodels can use for different things (currently just the beta approximation). Basically if you add this you must include the F(Q) function but then the beta approximation option will appear as a choice when that model gets multiplied with an S(Q).
* Page 28 - Note the ER function is deprecated and should probably not be used (and only works for pure python anyway I think).
* Page 27-28 - ALSO! Note that an effective radius function needs to be defined in order for the structure factor drop down to be enabled. Basically that is what tells sasmodels that this model can be paired with a structure factor.
* Page 28 - Model Normalization - this is really about the number average normalization. As I said before, not providing that MUST be accompanied by moving the 1/V into the model definition and then it will properly model the data but return z averages of parameters.
* Page 28 Shell volume – "must" is a strong word. Basically it is a way of ensuring that scale returns the volume fraction of material not of the object (assuming you are on absolute scale).

**Comment by smk78** [comment]
@butler wrote:
>Page 5 - Checking “overwrite” if the model is a built-in model could be a disaster, however it seems to just fail without announcing (i.e. fails but doesn’t pop up a box and exists the editor). I don’t know what happens if you do this with the simple model editor however.

The answer is... bad things! See https://github.com/SasView/sasview/issues/2611.

As far as the tutorial is concerned, I have added the following sentence in red font: 'It is unwise to overwrite library models or create models with the same names as library models!'.

**Comment by smk78** [comment]
@butlerpd wrote:
>Page 6 - Actually @ should normally be used for all P*S unless you
a) want only constrained radius and no beta approximation option and
b) want to simplify the model interface. Using @ does NOT leave radius unconstrained but offers all the usual options (unconstrained, constraint 1, 2, etc) and also offers an option to either use the beta approximation, if available, or not. To be honest, I think * is just there for completeness and historical reasons.

This has been revised to read:
![image](https://github.com/SasView/tutorials/assets/10938679/68f4a28d-1310-4a18-bb23-9a90c674b525)

**Comment by smk78** [comment]
@butler wrote:
>age 11 and 12 - Actually you do not need to assign Intensity to y since you explicitly return y. So I frequently do:
```
Intensity = A * sin(x)
Return intensity
```
>Which works just fine.

Yes, agreed. And @wpotrzebowski made a similar point. But some Users might be more comfortable using q and I, and it does improve code readability. I have revised the text to read:

![image](https://github.com/SasView/tutorials/assets/10938679/9945297c-5f91-4384-8612-7ddc7b5ffcdb)

Which I think clarifies sufficiently?

**Comment by smk78** [comment]
@butler wrote:
>Page 14 - Should mention what unit tests are for (not just say it is bad form to ignore). But it is described in section 6 along with appropriate references so here just a sentence about it followed by “see discussion in section 6" would be appropriate I think.

Done
![image](https://github.com/SasView/tutorials/assets/10938679/53aa6914-4930-449a-9bdc-7adf4bc32659)

**Comment by smk78** [comment]
@butler wrote:
>Page 16 - Actually I don’t think you ever need to import math. That is done automatically somewhere in sasmodels I think? Certainly you just need to use cos(x) or sin(x) etc without importing anything.
>For the “easy editor” specifically (Because it is meant to be “easy” 🙂 as long as you type np.array for example the editor will automatically add the import numpy as np statement for you. (note that the file created by the editor automatically adds a from numpy imp inf). Finally writing something like scipy.special.gamma(3) will get the editor to automatically add an import scipy statement.” This will not be the case of course when creating models from scratch (a different editor)

Thanks. I wasn't aware of this!

I think there is still value in elaborating the 'full form' for those with a little Python knowledge so have revised the text to say:
![image](https://github.com/SasView/tutorials/assets/10938679/43be0ae7-99e9-44ba-a480-33c24fc10505)

**Comment by smk78** [comment]
@butler wrote:
>WARNING HERE. You don’t add polydispersity in the example, but do mention it. It is probably worth noting that IF you declare something polydisperse (type volume) you need to provide a form_volume function later by going to the full model editor AND you need to write the function WITHOUT normalizing by volume which must get done by SasView to return the number average like all other models. If you do not, the returned value is the z average – this can be discussed in detail here or in section 6 where it appears again. Eventually I’m hoping we can add a pane that pops up as soon as polydisperse parameters are defined and asks for the code for form_volume. For now it is a bit of a dangerous trap for novice users.

Ahhh... good point!

I have added this Aside:
![image](https://github.com/SasView/tutorials/assets/10938679/810706f9-f925-4cec-b8ce-5a560fa469e7)

**Comment by smk78** [comment]
@butler wrote:
>Page 16 - The sentence motivating example 4 seems off… what does the model marketplace have to do with having something in the base models? I don’t understand what this means so guess nor will a new user?

Have changed the box from:
![image](https://github.com/SasView/tutorials/assets/10938679/86b092b3-cfde-49b1-83d7-9785929745b4)

to:
![image](https://github.com/SasView/tutorials/assets/10938679/b20517bc-685c-44b0-95f5-897ddcef039d)

**Comment by smk78** [comment]
@butler wrote:
>Page 17 - Name attribute. As far as I know it is still the name used internally by SasView so needs to be unique. Best if it matches exactly the .py name I think. that is mentioned much later but probably should be done here too? Particularly since the nature of this tutorial means some people may pick and choose which section is appropriate to them?

Indeed. But I think you missed that this section starts by reviewing the _correlation_length_ model itself and so it is correct that the name attribute still says _"correlation length"_.

As you noted, it is changed to _"example4"_ when we start changing the code.

No changes necessary here.

**Comment by smk78** [comment]
@butler wrote:
>Page 17 (and future like page 22/ Example 5) - SasView provides everything you need!! Why open a text editor or the file explorer etc) when you can just use the model editor and load any .py file in the plugin folder (or elsewhere for that matter using the plugin manager!!!)
>So for example 4 I would open the Manage Custom Models panel and click add file. From there navigate to the folders exactly as you describe. Pick the model and click on it. The beauty of this tool is that if the model is a python plus c, the manager will copy BOTH files to the plugin folder instantly. Because the model name exists it will automatically rename it to model_user internally, however it does not actually change the name of the file or the model name. I think, however, that this still works? But likely you will want to change the name anyway? Now choosing the model and clicking Edit will bring up the Editor …. With BOTH the py and c files already loaded if they exist. Of course for example 4 only the python file. The downside is that we currently do not have a button to rename the file (I don’t think?). From the Editor which has line numbers you can edit and apply etc..
>We wrote these very useful tools so we should be encouraging people to use them (otherwsie they won’t know they exist). I think I would just add a sentence that states “you are of course welcome to use any editor of your choice if you prefer, but will need to restart SasView …”

I guess the point is that the Model Editor has very limited functionality. But you make a fair point.

Have changed the text in both locations to:
![image](https://github.com/SasView/tutorials/assets/10938679/25d0f5bb-7d86-4a41-834a-4e415369011b)

**Comment by smk78** [comment]
@butler wrote:
>Page 16-17 - It may be a question of too much information at this point, but since model marketplace was mentioned, another place to get the models from is said marketplace? But maybe not.. Maybe TMI? In particular since we should focus on using the model manager which will get the files from the local directory.

Ok, I've modified the text in https://github.com/SasView/tutorials/issues/4#issuecomment-1722508310 to mention the Marketplace thus:
![image](https://github.com/SasView/tutorials/assets/10938679/fc58e511-3023-48cd-a07b-412e6de4d2e6)

**Comment by smk78** [comment]
@butler wrote:
>Page 24/25 - NICE showing polydisperse (R) vs not poly (Rg). What happens if you define Rg as “volume” that could be an interesting pedagogical exercise?

Beyond the scope of this document, as they say! ;-)

**Comment by smk78** [comment]
@butler wrote:
>Page 28 - Note the ER function is deprecated and should probably not be used (and only works for pure python anyway I think).

Have changed the text to read:
![image](https://github.com/SasView/tutorials/assets/10938679/21a5b9d6-7c70-4c2a-a3e3-00bab6176103)

**Comment by smk78** [comment]
@butler wrote:
>Page 27-28 - ALSO! Note that an effective radius function needs to be defined in order for the structure factor drop down to be enabled. Basically that is what tells sasmodels that this model can be paired with a structure factor.

Have added the following to the text:
![image](https://github.com/SasView/tutorials/assets/10938679/f8bc4245-5594-4315-ad16-a3b9f66e9904)

**Comment by smk78** [comment]
@butler wrote:
>Page 28 Shell volume – "must" is a strong word. Basically it is a way of ensuring that scale returns the volume fraction of material not of the object (assuming you are on absolute scale).

Have changed 'must' to 'should'.

**Comment by butlerpd** [comment]
Been watching the comments grow above as I could @smk78. Mostly looks good but have not had time to check a couple of things I was not sure about and definitely not seen the last entries.  I will try to address this but am way behind on getting organized to start driving EARLY Friday morning ☹️.

**Comment by smk78** [comment]
@astellhorn took a look at _r3 and thought that greater clarity about the permitted syntax of the _load_model_info_ string in a plugin model would be useful.

Have added the following to Example 3:
![image](https://github.com/SasView/tutorials/assets/10938679/de76fabc-eddf-496d-a7fe-c27a01ed482d)

**Comment by smk78** [comment]
_r4 uploaded to _draft_ branch following discussion in Code Camp end-of-day PR review meeting.

**Comment by smk78** [comment]
_r5 uploaded to _draft_ branch following further review by @astellhorn .
_r4& _r3 deleted.

**Comment by butlerpd** [comment]
@smk78 can we close this issue? I believe the tutorial is live?
